apiVersion: v1
kind: Service
metadata:
  name: ufotracker
  namespace: ufology
  labels:
    app: ufotracker
spec:
  type: ClusterIP
  selector:
    app: ufotracker
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
